# Config file for automatic testing at travis-ci.com

language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.9

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox-travis
    - pip install -U pre-commit
    - pre-commit run --all-files

# Command to run tests, e.g. python setup.py test
script: 
    - python setup.py test
    - pytest
# tox

cache:
    - pip
    - directories:
          - $HOME/.cache/pre-commit